$("#picAnswer").hide();

$("button").click(function(){
    $("#picAnswer").show();
    var weight = $("#weight").val();
    var element = $("#element").val().toLowerCase();
    if (weight <= 90 && element === "fire") {
     $("#title").html("Charmander");
     $("#answer").html("Charmander is a bipedal, reptilian Pokémon with a primarily orange body. Its underside from the chest down and soles are cream-colored. It has two small fangs visible in its upper jaw and two smaller fangs in its lower jaw. Charmander has blue eyes. Its arms and legs are short with four fingers and three clawed toes. A fire burns at the tip of this Pokémon's slender tail and has blazed there since Charmander's birth. The flame can be used as an indication of Charmander's health and mood, burning brightly when the Pokémon is strong, weakly when it is exhausted, wavering when it is happy, and blazing when it is enraged. It is said that Charmander dies if its flame goes out. However, if the Pokémon is healthy, the flame will continue to burn even if it gets a bit wet and is said to steam in the rain.Charmander can be found in hot, mountainous areas. However, it is found far more often in the ownership of Trainers. As shown in Pokémon Snap, Charmander exhibits pack behavior, calling others of its species if it finds food.");
     $("#picAnswer").attr("src", "http://static.pokemonpets.com/images/monsters-images-300-300/4-Charmander.png");
    } else if (weight >= 91 && element === "fire") {
        $("#title").html("Charizard");
     $("#answer").html("Charizard is a draconic, bipedal Pokémon. It is primarily orange with a cream underside from the chest to the tip of its tail, which burns with a sizable flame. Charizard has a long neck, small blue eyes, raised nostrils, and two horn-like structures protruding from the back of its rectangular head. There are two fangs visible in the upper jaw when its mouth is closed. Two large wings with blue-green undersides sprout from its back, and a horn-like appendage juts out from the third joint of each wing. Charizard's arms are short and skinny compared to its robust belly, and each limb has three white claws. It has stocky legs and cream-colored soles under its feet.");
     $("#picAnswer").attr("src", "http://www.stickpng.com/assets/images/5859662e4f6ae202fedf2878.png");
    } else if (weight <=90 && element === "water") {
        $("#title").html("Squirtle");
        $("#answer").html("Squirtle is a small Pokémon that resembles a light blue turtle. While it typically walks on its two short legs, it has been shown to run on all fours in Super Smash Bros. Brawl. It has large eyes and a slightly hooked upper lip. Each of its hands and feet has three pointed digits. The end of its long tail curls inward. Its body is encased by a tough shell that forms and hardens after birth. This shell is brown on the top, pale yellow on the bottom, and has a thick white ridge between the two halves. Squirtle's shell is a useful tool. It can withdraw into the shell for protection or for sleeping, and its grooved, rounded shape helps to reduce water resistance when this Pokémon swims. Squirtle can spray foamy water from its mouth with great accuracy. In the past, Skull Bash was its signature move. Squirtle is scarce in the wild, although it can be found around small ponds and lakes. The anime has shown that it can be found living on secluded islands with other members of its evolutionary line. ");
        $("#picAnswer").attr("src", "https://pre00.deviantart.net/86bf/th/pre/i/2011/141/b/2/squirtle_by_tranquilcomics-d3gvpni.png");
    } else if (weight >=91 && element === "water") {
        $("#title").html("Blastoise");
        $("#answer").html("Blastoise is a large, bipedal turtle-like Pokémon. Its body is blue and is mostly hidden by its tough, brown shell. This shell has a pale yellow underside and a white ridge encircling its arms and separating the upper and lower halves. Two powerful water cannons reside in the top sides of its shell. These cannons can be extended or withdrawn and can be used to assist in high-speed charges. Blastoise's head has triangular ears that are black on the inside, small brown eyes, and a cream-colored lower jaw. Its arms are thick and striated with three claws on each hand. Its feet have three claws on the front and one on the back. It has a stubby tail. As Mega Blastoise, it develops two smaller shells over its arms, each with their own water cannon. The two cannons on its back are replaced by a single, central water cannon of greater size. This cannon extends forward over Mega Blastoise's head and is said to have a blast range of over 6 miles (10 km).[1] Small ridges develop over its now-red eyes and extend to its ears. The ears angle slightly backward and there is a small point on its chin.");
        $("#picAnswer").attr("src", "https://usercontent2.hubstatic.com/13151003.png");
    }else if (weight <=91 && element === "air") {
        $("#title").html("Dragonair");
        $("#answer").html("Dragonair is a long, serpentine Pokémon with sky blue scales and a white underside. Its violet eyes are dark and glossy. It has a smooth, rounded snout and a small, white horn on its forehead. Its head is flanked by two small, stylized wings, which are white and curve into a swirl at the base. Three blue, crystal orbs, one on its neck and two on its tail, adorn its body. Dragonair emits a gentle aura that gives it a mystical appearance. As seen in the anime, it can make its wings grow larger in order to fly, but otherwise moves through the air unaided. Dragonair hosts a large amount of energy within its body, which it can discharge through the crystal orbs on its neck and tail. This causes its body to brighten and give off a different aura that changes the weather in its vicinity. Dragonair is a rare Pokémon that inhabits seas and lakes. ");
        $("#picAnswer").attr("src", "https://cdn.bulbagarden.net/upload/9/93/148Dragonair.png");
    }else if (weight >=91 && element === "air") {
        $("#title").html("Dragonite");
        $("#answer").html("Dragonite is a draconic, bipedal Pokémon with light orange skin. It has large, grayish-green eyes and a round snout with small nostrils. A pair of long, thin antennae sprout from the top of its head, with a small horn set between them. Its striated underbelly is cream-colored, and extends from its neck to the tip of its long, tapering tail. It has thick arms and legs ending in three claws each. The leg joints are well defined, while its arms have a smooth, rounded appearance. Dragonite's wings are small relative to its body, with teal wing membranes. Despite its bulky build, Dragonite is capable of flying faster than the speed of sound. It can circle the globe in sixteen hours, traveling roughly 1,556 mph (2,505 km/h), or about three times the speed of an average airplane. A kindhearted Pokémon with human-like intelligence, Dragonite shows signs of altruism: it is said to save humans from drowning and lead lost or foundering ships to safety. As demonstrated in the anime, however, it will go on an uncontrollable, destructive rampage if its environment is threatened. Dragonite is very rare in the wild, typically living near the sea. Some claim that there is an island somewhere in the ocean that only Dragonite inhabit.");
        $("#picAnswer").attr("src", "http://static.pokemonpets.com/images/monsters-images-300-300/8147-Mega-Dragonite-Blade.png");
    }else if (weight <=91 && element === "earth") {
        $("#title").html("Rhyhorn");
        $("#answer").html("Rhyhorn is a rhinoceros-like creature with a body covered in gray, rocky plates. Its underside and rear are smooth, and it has four short legs with two claws on each foot. It has a triangular head with narrow, red eyes, two fangs protruding from its upper jaw, and small, triangular openings on the upper sides. A spiked ridge runs along its back, and it has a single short horn on the tip of its snout. The female has a shorter horn than the male. In addition to its rocky hide, its bones are a thousand times harder than human bones. Rhyhorn's brain is very small, giving it a one-track mind. When it runs, it forgets why it started and continues until it falls asleep. However, it may recall the reason upon demolishing something. Rhyhorn runs in a straight line due to its short legs making it inept at turning. It does not care if obstacles get in the way, merely smashing through them or sending them flying. Sometimes it may feel pain the day after a collision. Rhyhorn lives in rough terrain.");
        $("#picAnswer").attr("src", "https://vignette.wikia.nocookie.net/vsbattles/images/3/36/Rhyhorn.png/revision/latest?cb=20161111040049");
    }else if (weight >=91 && element === "earth") {
        $("#title").html("Rhyperior");
        $("#answer").html("Rhyperior is a large, brownish-gray Pokémon with two horns: one on its nose, and another one above it. The upper horn is smaller on a female Rhyperior. It has a club-like tail and its hide is partially covered by orange, rocky plates. It has blade-like protrusions on its elbows and has holes in the palms of its hands which works as a cannon or a gun. Rhyperior can insert rocks and boulders into its arms through the holes in its hands and then fire them like bullets. However, it will occasionally insert and fire Geodude by accident. It also appears to have two thick, rectangular rocks above its eyes, resembling heavy eyebrows. Rhyperior lives far up in the mountains.");
        $("#picAnswer").attr("src", "http://static.pokemonpets.com/images/monsters-images-300-300/8463-Mega-Rhyperior.png");
    } 
    else {
        $("#title").html("Oops!");
        $("#answer").html("You didn't choose one of my options! Try again!");
        $("#picAnswer").attr("src", "http://www.rupertgrintpress.com/wp-content/uploads/2010/10/gofmed027.jpg");
    }
});